#!/usr/bin/python
import time
from ibquery import InfoBeamerQuery

while 1:
    ib = InfoBeamerQuery("127.0.0.1")
    con = ib.node("display/atomic").io(raw=True)
    con.write("Hello\nWorld\n%d\n" % time.time())
    con.close()

    time.sleep(1)