#!/usr/bin/python
import datetime
from ibquery import InfoBeamerQuery

while 1:
    ib = InfoBeamerQuery("127.0.0.1")
    x = datetime.datetime()
    con = ib.node("display/atomic").io(raw=True)
    con.write("\n\nVÄLKOMMEN TILL\nJAMBOREE26\n\n%d\n" % x.strftime('%Y-%m-%d %H:%M:%S'))
    con.close()

    time.sleep(1)